# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f4b36e6999354156eaca4436b79b457eaaa7f29a492294751d3c1cef073ae3244c78b6e41163ec1aa79fe33af7273128aa68b916913759c70ac5c0a413f6758

test:
  secret_key_base: 9bfc1a9f2546305589152c102bbb0d160df21a385334fd5778bf79a5db47ef3a2d723bb8308ffc0749f9100c96ee4323f6eb1484f91157a6acf9b920e27dd7e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
